### ISSUE TITLE
Add Hetzner Plugin

### ISSUE THREAD

**Issue by 4rr0wx** [invoiceradar/plugins#31]
[hetzner.json](https://github.com/user-attachments/files/16849474/hetzner.json)

I made an first draft for an Hetzner plugin.
Please check for errors. I've tried it and it works for me

**Comment by timolins** [comment]
Amazing, thank you! I made a couple small tweaks (e.g. added support for amounts) and added it to the repo: https://github.com/invoiceradar/plugins/commit/6c353022ff4b5bc0cc6835b9739de31b42659161
