### ISSUE TITLE
Add Cloud convert Plugin

### ISSUE THREAD

**Issue by 4rr0wx** [invoiceradar/plugins#33]
I created an Plugin for CloudConvert.
[cloud-convert.json](https://github.com/user-attachments/files/16980454/cloud-convert.json)

**Comment by timolins** [comment]
Thank you, added! https://github.com/invoiceradar/plugins/commit/b97e0c1b8a8ea80aba6b793344f5ea80bdaeaca0

Just a friendly tip for the future: consider making it a PR! It’ll help us collaborate on changes more easily. 👍
